[2025-05-08 13:27] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:27] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:33] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:33] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:33] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:33] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:34] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:34] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:36] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:36] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:36] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:37] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:37] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:37] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:37] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:37] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:37] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:40] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:40] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:40] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:40] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:40] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:40] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:40] [logger.py|_log] [line:78] ERROR   : 连接 Milvus 失败: <MilvusException: (code=2, message=Fail connecting to server on milvus:19530, illegal connection params or server unavailable)>
[2025-05-08 13:42] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:42] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:42] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:42] [logger.py|_log] [line:78] ERROR   : 连接 Milvus 失败: <MilvusException: (code=2, message=Fail connecting to server on milvus:19530, illegal connection params or server unavailable)>
[2025-05-08 13:44] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:44] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:44] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:44] [logger.py|_log] [line:78] ERROR   : 连接 Milvus 失败: <MilvusException: (code=2, message=Fail connecting to server on milvus:19530, illegal connection params or server unavailable)>
[2025-05-08 13:45] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:45] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:45] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:45] [logger.py|_log] [line:74] INFO    : Milvus 已连接: http://localhost:19530
[2025-05-08 13:46] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:46] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:46] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:46] [logger.py|_log] [line:74] INFO    : Milvus 已连接: http://localhost:19530
[2025-05-08 13:46] [logger.py|_log] [line:74] INFO    : Milvus 已连接: http://localhost:19530
[2025-05-08 13:50] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:50] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:50] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:50] [logger.py|_log] [line:74] INFO    : Milvus 已连接: http://localhost:19530
[2025-05-08 13:50] [logger.py|_log] [line:74] INFO    : Milvus 已连接: http://localhost:19530
[2025-05-08 13:53] [logger.py|_log] [line:74] INFO    : Loading config from saves/config/base.yaml
[2025-05-08 13:53] [logger.py|_log] [line:76] WARNING : 

======================================================================
                        Config file not found                         
        You can custum your config in `saves/config/base.yaml`        
======================================================================


[2025-05-08 13:53] [logger.py|_log] [line:76] WARNING : 提醒：MODEL_DIR （D:/Huggingface） 不存在，如果未配置，请忽略，如果配置了，请检查是否配置正确，比如 docker-compose 文件中的映射
[2025-05-08 13:53] [logger.py|_log] [line:74] INFO    : Milvus 已连接: http://localhost:19530
[2025-05-08 13:53] [logger.py|_log] [line:74] INFO    : Milvus 已连接: http://localhost:19530
